### ISSUE TITLE
ModuleNotFoundError: No module named 'machine'

### ISSUE THREAD

**Issue by Kakcalu13** [Krakenus/microbit-cutebot-micropython#3]
My apologies if this question may seem a little silly. 

For some reason, i was not able to run smart cutebot using python 3.9 (outside of all links you mentioned on doc).

I'm not sure how you are able to run cutebot after import machine and utime which are also from micropython package. See here,

```
bwuk@robots:~/bitio/src$ pip3 install micropython-upip
Defaulting to user installation because normal site-packages is not writeable
Collecting micropython-upip
  Using cached micropython-upip-1.2.6.tar.gz (4.3 kB)
ERROR: micropython-upip from https://files.pythonhosted.org/packages/29/81/52df27cb7d240190c1d3ddab0c081bd3296bedcce155eed9e7016c4d92f0/micropython-upip-1.2.6.tar.gz#sha256=b9c09fc2b65f877d945142e468e0f25b5f70e9f74e98e0f43ca030bd7f47e87f does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

```

This was called by cutebot.py which has `import machine`. 

See here:
![image](https://user-images.githubusercontent.com/65916520/158696247-3233b4d9-5621-490d-95d4-820555057b41.png)

Now the question is did I use the right package for this?

**Comment by Kakcalu13** [comment]
I even ran [requirements.txt ](https://github.com/Krakenus/microbit-micropython-bakefile)as well too

**Comment by Krakenus** [comment]
@Kakcalu13 Hello, the `cutebot.py` module is not ment to be used with regular cpython intepreter. Only with micropython for micro:bit board. That's the reason why you get the `ModuleNotFoundError`. Because the `machine` package exists only in  the micropython.

Maybe you could be able to run it with unix port of micropython but still it requires specific hardware module to work correctly.
https://github.com/micropython/micropython

For the `requirements.txt` you mentioned: Those are requirements for console scripts from my other repo and have no connection to this library (except it's for micro:bit as well).

**Comment by Kakcalu13** [comment]
Thank you for the quick reply! Truly appreciate it! 

Okay, I will check it out asap! If it fixed my issue, I will post the solution and close it! :)

**Comment by Kakcalu13** [comment]
Seems no luck.


I ran on unix and it seemed OK until I ran `./micropython -m upip install micropython-pystone` and its having issues. 

I'm kinda convinced that this is not on cutebot's end. It's outside of this place at the moment. I will continue digging on that one.

**Comment by Krakenus** [comment]
Yes, it's definitely not connected with cutebot or this repo.

**Comment by Kakcalu13** [comment]
Closing the issue as this is confirmed that it's not from this repo or cutebot. It's related to micropython issue

Will post the solution for anyone who came to the same issue as me anyway

**Comment by Kakcalu13** [comment]
I almost forgot to post.

So, basically that micro python isn't a library. It's an IDE for microprocessors. So you need to upload your code INSIDE micro python, not just the normal and regular python. :| 

python3 = micro python and microbit libraries are already inside micro python btw.
